- name: "7.8.9 Ensure dnsmasq services are not in use" 
  ansible.builtin.service:
    name: dnsmasq
    state: stopped
  ignore_errors: yes
#------------------------------------------------
#OS = RHEL 7,8,9	7,8(2.2.9) 9(2.1.9)	Ensure network file system services are not in use 

- name: "2.2.9 Ensure network file system services are not in use "
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - nfs-server
    - rpcbind
  ignore_errors: yes

- name: " 2.2.9 Ensure nfs-utils package is removed"
  ansible.builtin.package:
    name: nfs-utils
    state: absent
  ignore_errors: yes

#-------------------------------------------------

#OS = RHEL 7,8,9	7,8(2.2.10) 9(2.1.10)	Ensure nis server services are not in use 
- name: "2.2.10 Ensure nis server services are not in use"
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop:
    - ypserv
    - yppasswdd
    - ypbind
  ignore_errors: yes

- name: Remove NIS server packages
  ansible.builtin.package:
    name:
      - ypserv
      - ypbind
    state: absent
  ignore_errors: yes


  - name: Stop and disable rsyncd service
    ansible.builtin.service:
      name: rsyncd
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: Remove rsync package (optional)
    ansible.builtin.package:
      name: rsync
      state: absent
    ignore_errors: yes
